#!/usr/bin/env node
// codemap QA pass — optional tooling, NOT part of the zero-dependency core app.
// codemap.py / lib/ / template.html ship with no third-party dependencies;
// this script is dev/CI tooling only and requires `playwright` (see README's
// QA section: `npm i playwright` once, or point NODE_PATH at an existing
// install). Nothing in qa/ is imported by the core app.
//
// Usage: node qa/map-qa.mjs <path-to-codemap.html>
//
// Regenerate the file under test first, e.g.:
//   python3 codemap.py render tests/fixtures/toyrepo
//   node qa/map-qa.mjs tests/fixtures/toyrepo/.codemap/codemap.html
//
// Four QA surfaces are expected to stay green, each pre-generated by the
// caller (this script never shells out to python, so it stays a pure browser
// harness and can run against any map file):
//   python3 codemap.py render tests/fixtures/toyrepo              (zero IaC)
//   python3 codemap.py render <any real repo>  (zero IaC, full labels + lenses)
//   python3 codemap.py render tests/fixtures/iacrepo              (IaC: infra graph + roles, multi-group)
//   python3 codemap.py render tests/fixtures/multienvrepo         (IaC: envs/prod + envs/dev, environments chips)
//
// What it checks (see report below for the live pass/fail per item):
//  1. No pageerror while loading the map.
//  2. Overview and System tabs render; screenshots saved. On a map WITH IaC
//     data the System tab must show the infra graph: at least one role box,
//     every arrow endpoint landing inside a real box, mechanism labels
//     appearing on hover, and clicking a role opening a peek whose grants
//     table has one row per grant in DATA. On a map WITHOUT IaC data it must
//     still show the legacy boundaries row and no infra graph at all. On the
//     IaC map, synthetic gh-shaped data is also injected to prove the
//     deployed chip renders one chip per workflow, colors a failed
//     conclusion and a commit-mismatched sha amber, and disappears entirely
//     when DATA.iac.deployed is empty (its real, non-test dormant state).
//  3. Code tab, at root and at the two densest drillable levels found by
//     walking into the child with the most children (max depth 3): for
//     every box, hovering it must light exactly as many edge paths as that
//     box has in DATA (the pruning bug this script exists to catch: pruned
//     edges must still exist in the DOM, just hidden, so hover can reveal
//     them); zero duplicate (src,dst) paths per level; if a prune chip
//     exists, toggling it must drop hidden-edge count to zero and restore it.
//  4. Canvas usage: on any tested level with more than 6 boxes, the union
//     bounding box of the boxes must cover at least 40% of the viewport area
//     (the fixed 100x62 letterbox this replaced wasted most of the page), and
//     at most 250% of it (and no wider than 1.5x the viewport) for levels up to
//     15 boxes: sprawling across screens of empty canvas wastes the page just as
//     badly the other way. Bigger levels get the floor only; they do scroll.
//  5. Label collision: on the densest level, no visible edge label may overlap
//     any box by more than 4px on both axes (dagre reserves a rank for every
//     labeled edge; a regression here means labels stopped using it).
//  6. If lenses exist: activating each leaves every box in exactly one of
//     .lit / .dimmed (never neither, never both); every lens-lit arrow lands on
//     a box that is itself .lit at opacity >= 0.9 (no arrows into blackness);
//     no box falls below opacity 0.4 (the dim floor); one lens state screenshot.
//  7. Exclusive focus: with a lens active AND a box hovered, the visible lit
//     edges are exactly that box's edges, never the lens+hover union.
//  8. Environments (System tab): every infra box shows a group badge naming
//     a real group. When the map has more than one distinct group, an
//     "Environments" chip row renders above the infra graph listing exactly
//     those groups; activating one lights its own boxes and dims (only) the
//     rest, and a second click clears it. A synthetic single-group re-render
//     proves the row disappears entirely when there's nothing to distinguish.

import path from 'node:path';
import fs from 'node:fs';
import { pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';

// Node's ESM resolver ignores NODE_PATH (unlike CJS require), so resolve
// playwright through createRequire — this is what lets `NODE_PATH=<an
// existing install> node qa/map-qa.mjs ...` work without a local install.
const { chromium } = createRequire(import.meta.url)('playwright');

const results = []; // {ok, label}
function check(ok, label) {
  results.push({ ok, label });
  console.log((ok ? 'PASS' : 'FAIL') + ' ' + label);
  return ok;
}

function escAttr(s) {
  return String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

// Boxes fade in on a staggered "rise" animation, so anything that reads back an
// opacity or a geometry has to wait for the level to stop moving or it measures
// a mid-fade value and reports a styling bug that isn't there. Two passes: the
// first outlives closePeek's deferred re-render (a 210ms timer that rebuilds
// every box, restarting their animations), the second waits out whatever that
// re-render started.
async function settle(page) {
  const anims = () => page.evaluate(() =>
    Promise.all(document.getAnimations().map((a) => a.finished.catch(() => {}))));
  await page.waitForTimeout(260);
  await anims();
  await page.waitForTimeout(60);
  await anims();
}

// ---- System tab (v2): infra graph when DATA.iac has anything, legacy row when not.
// Assumes the System tab is already showing and settled.
async function testSystemTab(page, qaOutDir, label, ctx) {
  const iac = await page.evaluate(() => {
    const m = (typeof DATA !== 'undefined' && DATA.iac) || {};
    return { resources: (m.resources || []).length, roles: (m.roles || []).length,
             connections: (m.connections || []).length };
  });

  if (!iac.resources && !iac.roles) {
    // Zero-IaC repos must render exactly as before: boundaries row, no graph.
    const legacy = await page.evaluate(() => ({
      graph: !!document.getElementById('sysgraph'),
      boundaryBoxes: document.querySelectorAll('#sys-boundaries .stage-box').length,
      pipelineBoxes: document.querySelectorAll('#canvas .pipeline .stage-box').length,
    }));
    check(!legacy.graph && legacy.boundaryBoxes > 0,
      `system (no IaC): legacy boundaries row kept, no infra graph (${legacy.boundaryBoxes} boundary boxes, graph=${legacy.graph})`);
    check(legacy.pipelineBoxes > 0, `system (no IaC): pipeline strip still rendered (${legacy.pipelineBoxes} stages)`);
    return;
  }

  console.log(`-- system tab: ${iac.resources} resources, ${iac.roles} roles, ${iac.connections} connections --`);

  const shape = await page.evaluate(() => ({
    graph: !!document.getElementById('sysgraph'),
    boxes: document.querySelectorAll('#sysgraph .box').length,
    roleBoxes: document.querySelectorAll('#sysgraph .box.sys-role').length,
    roleArrows: document.querySelectorAll('#sysgraph svg path.flow-line.edge-kind-role').length,
    legacy: !!document.getElementById('sys-boundaries'),
  }));
  check(shape.graph && shape.roleBoxes > 0,
    `system: infra graph renders with role boxes (${shape.boxes} boxes, ${shape.roleBoxes} roles)`);
  check(!shape.legacy, 'system: legacy boundaries row replaced by the infra graph');

  // Every arrow must terminate on a real box. Both path endpoints are mapped
  // from user units to screen coords and tested for containment (with a small
  // tolerance) in some box's rect: an arrow pointing into empty canvas means a
  // node the layout never drew, which is the defect this guards.
  const arrows = await page.evaluate((tol) => {
    const host = document.getElementById('sysgraph');
    const svg = host && host.querySelector('svg');
    if (!svg) return { total: 0, bad: ['no svg'], worst: 0 };
    const boxes = [...host.querySelectorAll('.box')].map((b) => b.getBoundingClientRect());
    const gap = (x, y) => Math.min(...boxes.map((r) =>
      Math.max(0, r.left - x, x - r.right) + Math.max(0, r.top - y, y - r.bottom)));
    const bad = [];
    let worst = 0;
    const paths = [...svg.querySelectorAll('path.flow-line')];
    for (const p of paths) {
      const m = p.getScreenCTM();
      const len = p.getTotalLength();
      for (const at of [0, len]) {
        const pt = p.getPointAtLength(at);
        const sp = new DOMPoint(pt.x, pt.y).matrixTransform(m);
        const d = gap(sp.x, sp.y);
        worst = Math.max(worst, d);
        if (d > tol) bad.push(`${p.dataset.src} -> ${p.dataset.dst} @${at === 0 ? 'start' : 'end'} ${Math.round(d)}px off`);
      }
    }
    return { total: paths.length, bad, worst: Math.round(worst) };
  }, 8);
  arrows.bad.slice(0, 5).forEach((b) => console.log('  ' + b));
  check(arrows.total > 0 && arrows.bad.length === 0,
    `system: every arrow terminates on a box (${arrows.total} arrows, worst endpoint gap ${arrows.worst}px, ${arrows.bad.length} off-box)`);

  // Mechanism labels are calm by default and appear on hover, same grammar as
  // the Code tab. Every box that has an arrow must show at least one label.
  const boxNames = await page.evaluate(() =>
    [...document.querySelectorAll('#sysgraph .box[data-boxname]')].map((b) => b.dataset.boxname));
  let silentHovers = [], viaRoleLabels = 0, labelSightings = 0;
  for (const name of boxNames) {
    const loc = page.locator(`#sysgraph .box[data-boxname="${escAttr(name)}"]`);
    if ((await loc.count()) === 0) continue;
    await loc.hover();
    await page.waitForTimeout(30);
    const seen = await page.evaluate((n) => {
      const host = document.getElementById('sysgraph');
      const hasEdge = !!host.querySelector(
        `svg path.flow-line[data-src="${CSS.escape(n)}"], svg path.flow-line[data-dst="${CSS.escape(n)}"]`);
      const labels = [...host.querySelectorAll('svg text.flow-label')]
        .filter((el) => getComputedStyle(el).display !== 'none')
        .map((el) => el.textContent);
      return { hasEdge, labels };
    }, name);
    labelSightings += seen.labels.length;
    viaRoleLabels += seen.labels.filter((t) => t.startsWith('via ')).length;
    if (seen.hasEdge && seen.labels.length === 0) silentHovers.push(name);
    await page.mouse.move(0, 0);
    await page.waitForTimeout(15);
  }
  silentHovers.slice(0, 5).forEach((n) => console.log(`  hover "${n}" lit no mechanism label`));
  check(silentHovers.length === 0,
    `system: hovering a connected box reveals its mechanism labels (${boxNames.length} boxes, ${labelSightings} label sightings, ${silentHovers.length} silent)`);
  check(viaRoleLabels > 0 || shape.roleArrows === 0,
    `system: "via <role>" labels appear on hover (${viaRoleLabels} sightings across ${shape.roleArrows} role arrows)`);

  // Click a role box -> peek with a grants table, one row per grant in DATA.
  const roleProbe = await page.evaluate(() => {
    if (typeof iacIndex === 'undefined' || !iacIndex) return null;
    const hit = Object.keys(iacIndex.byId)
      .map((id) => iacIndex.byId[id])
      .filter((n) => n.kind === 'role' && (n.role.grants || []).length > 0)
      .sort((a, b) => a.id.localeCompare(b.id))[0];
    return hit ? { id: hit.id, name: hit.role.name, grants: hit.role.grants.length,
                   src: `${hit.role.source_file}:${hit.role.line}` } : null;
  });
  if (!roleProbe) {
    check(false, 'system: found a role with grants to click');
    return;
  }
  await page.locator(`#sysgraph .box[data-boxname="${escAttr(roleProbe.id)}"]`).click();
  await page.waitForTimeout(400); // outlives the peek's 210ms re-layout timer
  const peek = await page.evaluate(() => ({
    open: document.getElementById('peek').classList.contains('open'),
    rows: document.querySelectorAll('#peek table.grants tbody tr').length,
    head: (document.querySelector('#peek .peek-head .fn') || {}).textContent || '',
    pathLine: (document.querySelector('#peek .peek-path') || {}).textContent || '',
    text: document.getElementById('peekInner').textContent,
  }));
  check(peek.open && peek.rows === roleProbe.grants,
    `system: clicking role "${roleProbe.name}" opens a peek with its grants table (${peek.rows}/${roleProbe.grants} rows)`);
  check(peek.head === roleProbe.name && peek.pathLine === roleProbe.src,
    `system: role peek names the role and its source line (${peek.head} @ ${peek.pathLine})`);
  check(/Attached to/.test(peek.text) && /Why/.test(peek.text),
    'system: role peek carries attached-to and why sections');
  await page.screenshot({ path: path.join(qaOutDir, `${label}-system-role-peek.png`) });
  await page.evaluate(() => closePeek());
  await page.waitForTimeout(300);

  // Deployed chip (lib/deployed.py's `gh run list` enrichment). No test fixture
  // has a live GitHub remote, so a real fetch never populates DATA.iac.deployed
  // here -- this proves the rendering contract (shape -> chip markup) directly
  // by injecting synthetic gh-shaped data into the already-loaded page and
  // re-invoking the same renderSystem() the tab switch itself calls, then
  // clearing it again to prove the dormant (no chip) state too.
  const depState = await page.evaluate(() => {
    const mapSha = DATA.meta.commit || '0000000';
    const matchingSha = mapSha.padEnd(40, '0');
    const driftSha = 'f'.repeat(40);
    DATA.iac.deployed = {
      workflows: [
        { workflow: 'qa-match', status: 'completed', conclusion: 'success',
          sha: matchingSha, at: new Date().toISOString(), url: 'https://example.com/match' },
        { workflow: 'qa-drift', status: 'completed', conclusion: 'failure',
          sha: driftSha, at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
          url: 'https://example.com/drift' },
      ],
      fetched_at: new Date().toISOString(),
    };
    renderSystem();
    return { mapSha };
  });
  await page.waitForTimeout(150);
  const chips = await page.evaluate(() => [...document.querySelectorAll('.dep-chip')].map((el) => ({
    workflow: el.dataset.workflow,
    classes: [...el.classList],
    title: el.getAttribute('title') || '',
    text: el.textContent,
  })));
  check(chips.length === 2, `system: deployed chip renders one chip per workflow (${chips.length}/2)`);
  const match = chips.find((c) => c.workflow === 'qa-match');
  const drift = chips.find((c) => c.workflow === 'qa-drift');
  check(!!match && !match.classes.includes('fail') && !match.classes.includes('stale'),
    `system: deployed chip on a matching-commit success run stays calm (classes: ${match ? match.classes.join(' ') : 'missing'}, mapSha=${depState.mapSha})`);
  check(!!match && /qa-match/.test(match.text) && /success/.test(match.text),
    `system: deployed chip shows workflow name and conclusion (${match ? match.text : 'missing'})`);
  check(!!drift && drift.classes.includes('fail') && drift.classes.includes('stale'),
    `system: deployed chip flags a failed conclusion and a commit mismatch (classes: ${drift ? drift.classes.join(' ') : 'missing'})`);
  check(!!drift && drift.title === 'map generated from a different commit than last CI run',
    `system: mismatch chip carries the explanatory title (${drift ? drift.title : 'missing'})`);
  await page.screenshot({ path: path.join(qaOutDir, `${label}-system-deployed-chip.png`) });

  // Dormant state: an empty deployed object renders no chip at all.
  await page.evaluate(() => { DATA.iac.deployed = {}; renderSystem(); });
  await page.waitForTimeout(150);
  const chipsAfterClear = await page.evaluate(() => document.querySelectorAll('.dep-chip').length);
  check(chipsAfterClear === 0, 'system: deployed chip is dormant (no chip) when DATA.iac.deployed is empty');

  // ---- Untrusted deployed.json ----
  // .codemap/deployed.json is a cache file on disk, baked into the page
  // verbatim on the next render. It is not a trusted input: anything that can
  // write into the repo can put a `javascript:` URL in it, and the chip used
  // to become an anchor around whatever string arrived. Only http(s) may
  // become a link; anything else must render as inert text.
  const dialogsBefore = ctx.dialogs.length;
  await page.evaluate(() => {
    DATA.iac.deployed = {
      workflows: [{ workflow: 'qa-poison', status: 'completed', conclusion: 'success',
                    sha: 'a'.repeat(40), at: new Date().toISOString(),
                    url: 'javascript:alert("codemap-xss")' }],
      fetched_at: new Date().toISOString(),
    };
    renderSystem();
  });
  await page.waitForTimeout(150);
  const poison = await page.evaluate(() => {
    const el = document.querySelector('.dep-chip[data-workflow="qa-poison"]');
    return {
      rendered: !!el,
      inAnchor: !!(el && el.closest('a')),
      jsHrefs: [...document.querySelectorAll('a[href]')]
        .filter((a) => /^\s*javascript:/i.test(a.getAttribute('href') || '')).length,
    };
  });
  check(poison.rendered && !poison.inAnchor && poison.jsHrefs === 0,
    `system: a javascript: URL in deployed.json renders as inert text, never a link (chip=${poison.rendered}, wrapped in <a>=${poison.inAnchor}, javascript: hrefs=${poison.jsHrefs})`);
  // and prove it by clicking: an executing javascript: href fires an alert
  const poisonChip = page.locator('.dep-chip[data-workflow="qa-poison"]');
  if (await poisonChip.count()) {
    await poisonChip.click({ force: true }).catch(() => {});
    await page.waitForTimeout(200);
  }
  check(ctx.dialogs.length === dialogsBefore,
    `system: clicking the poisoned chip executes nothing (${ctx.dialogs.length - dialogsBefore} dialog(s) fired${ctx.dialogs.length > dialogsBefore ? ': ' + ctx.dialogs.slice(dialogsBefore).join(' | ') : ''})`);

  // Malformed deployed.json (hand-edited, truncated write, wrong tool): a
  // non-array `workflows` must not take the whole System tab down with it.
  // The canvas is cleared first so "the graph is there" means this render
  // produced it, not that the previous one's markup survived.
  const errsBefore = ctx.pageErrors.length;
  const malformed = await page.evaluate(() => {
    DATA.iac.deployed = { workflows: 'boom' };
    document.getElementById('canvas').innerHTML = '';
    let threw = null;
    try { renderSystem(); } catch (e) { threw = String((e && e.message) || e); }
    return { threw, graph: !!document.getElementById('sysgraph'),
             chips: document.querySelectorAll('.dep-chip').length };
  });
  await page.waitForTimeout(150);
  check(!malformed.threw && malformed.graph && malformed.chips === 0 && ctx.pageErrors.length === errsBefore,
    `system: malformed deployed.json ({"workflows":"boom"}) still renders the infra graph (graph=${malformed.graph}, chips=${malformed.chips}, threw=${malformed.threw || 'no'}, ${ctx.pageErrors.length - errsBefore} pageerrors)`);

  // leave the page in its real dormant state for anything that follows
  await page.evaluate(() => { DATA.iac.deployed = {}; renderSystem(); });
  await page.waitForTimeout(150);

  // ---- Environments (task: environment visibility) ----
  // Every box carries a group badge (lib/iac.py group_of, baked at scan_iac
  // time). When the real map has more than one distinct group, an
  // "Environments" chip row appears above the infra graph, same interaction
  // grammar as the Code tab's #lensbar: click lights that group's boxes
  // (.lit) and dims (.dimmed) everything else, a second click clears it.
  const groups = await page.evaluate(() => iacGroups());
  console.log(`-- environments: ${groups.length} group(s): ${groups.join(', ')} --`);
  const badgeState = await page.evaluate(() => {
    const badges = [...document.querySelectorAll('#sysgraph .box .group-badge')];
    return { boxes: document.querySelectorAll('#sysgraph .box').length, badges: badges.length,
             texts: badges.map((b) => b.textContent) };
  });
  check(badgeState.badges === badgeState.boxes && badgeState.badges > 0,
    `system: every box shows a group badge (${badgeState.badges}/${badgeState.boxes})`);
  check(badgeState.texts.every((t) => groups.includes(t)),
    `system: every group badge names a real group (${[...new Set(badgeState.texts)].join(', ')})`);

  if (groups.length > 1) {
    const barShape = await page.evaluate(() => {
      const bar = document.getElementById('envbar');
      return { exists: !!bar,
               chips: bar ? [...bar.querySelectorAll('.env-chip')].map((c) => c.dataset.group) : [] };
    });
    check(barShape.exists, `system: environments chip row renders when >1 group present (${groups.length} groups)`);
    const sortedChips = barShape.chips.slice().sort();
    const sortedGroups = groups.slice().sort();
    check(JSON.stringify(sortedChips) === JSON.stringify(sortedGroups),
      `system: chip row lists exactly the groups in DATA (chips: ${sortedChips.join(', ')} | data: ${sortedGroups.join(', ')})`);

    // activate one group: every in-group box must be .lit (never .dimmed) and
    // every out-of-group box must be .dimmed (never .lit) -- the same
    // lit-xor-dimmed contract already enforced for Code-tab lenses above.
    const target = groups[0];
    const activation = await page.evaluate((g) => {
      const chip = [...document.querySelectorAll('#envbar .env-chip')].find((c) => c.dataset.group === g);
      if (!chip) return null;
      chip.click();
      // renderEnvBar rebuilds #envbar's innerHTML on every click (same
      // full-rebuild grammar as renderLensBar), which detaches the `chip`
      // node just clicked -- re-query the live DOM for its post-click state
      // rather than reading stale classes off the now-orphaned element.
      const chipAfter = [...document.querySelectorAll('#envbar .env-chip')].find((c) => c.dataset.group === g);
      const boxes = [...document.querySelectorAll('#sysgraph .box[data-boxname]')];
      const wrong = [];
      for (const b of boxes) {
        const node = iacIndex.byId[b.dataset.boxname];
        const grp = node && ((node.res && node.res.group) || (node.role && node.role.group));
        const inGroup = grp === g;
        const lit = b.classList.contains('lit');
        const dimmed = b.classList.contains('dimmed');
        if (lit === dimmed) wrong.push(`${b.dataset.boxname}: lit===dimmed (${lit})`);
        else if (inGroup && !lit) wrong.push(`${b.dataset.boxname}: in-group (${grp}) but not lit`);
        else if (!inGroup && !dimmed) wrong.push(`${b.dataset.boxname}: out-of-group (${grp}) but not dimmed`);
      }
      return { total: boxes.length, chipActive: !!chipAfter && chipAfter.classList.contains('active'), wrong };
    }, target);
    if (activation) activation.wrong.slice(0, 6).forEach((w) => console.log('  ' + w));
    check(!!activation && activation.chipActive && activation.wrong.length === 0,
      `system: activating group "${target}" lights only its own boxes and dims the rest (${activation ? activation.total : 0} boxes checked, ${activation ? activation.wrong.length : '?'} wrong)`);
    await settle(page);
    await page.screenshot({ path: path.join(qaOutDir, `${label}-system-env-${target.replace(/[^a-z0-9-]+/gi, '_')}.png`) });

    // second click on the same chip clears the filter entirely
    const cleared = await page.evaluate((g) => {
      const chip = [...document.querySelectorAll('#envbar .env-chip')].find((c) => c.dataset.group === g);
      if (chip) chip.click();
      // same stale-node caveat as above: re-query after the rebuild.
      const chipAfter = [...document.querySelectorAll('#envbar .env-chip')].find((c) => c.dataset.group === g);
      const boxes = [...document.querySelectorAll('#sysgraph .box')];
      return { chipActive: !!chipAfter && chipAfter.classList.contains('active'),
               anyLitOrDimmed: boxes.some((b) => b.classList.contains('lit') || b.classList.contains('dimmed')) };
    }, target);
    check(!cleared.chipActive && !cleared.anyLitOrDimmed,
      `system: clicking the active chip again clears the group filter (chip active=${cleared.chipActive}, boxes still lit/dimmed=${cleared.anyLitOrDimmed})`);
  } else {
    const noBar = await page.evaluate(() => !document.getElementById('envbar'));
    check(noBar, `system: this map has only ${groups.length} group -- no environments chip row rendered`);
  }

  // Synthetic single-group check, same "mutate DATA + re-render, then
  // restore" pattern as the deployed-chip tests above: forces every resource
  // under one group so the "single-group map has no chip row" contract is
  // proven directly, independent of how many groups the real map happens to
  // have (iacrepo and multienvrepo both legitimately have >1).
  const singleGroupState = await page.evaluate(() => {
    const savedResources = DATA.iac.resources.map((r) => r.group);
    const savedRoles = DATA.iac.roles.map((r) => r.group);
    DATA.iac.resources.forEach((r) => { r.group = 'only'; });
    DATA.iac.roles.forEach((r) => { r.group = 'only'; });
    activeGroup = null;
    renderSystem();
    const noBar = !document.getElementById('envbar');
    const badgeTexts = [...document.querySelectorAll('#sysgraph .group-badge')].map((b) => b.textContent);
    const allOnly = badgeTexts.length > 0 && badgeTexts.every((t) => t === 'only');
    DATA.iac.resources.forEach((r, i) => { r.group = savedResources[i]; });
    DATA.iac.roles.forEach((r, i) => { r.group = savedRoles[i]; });
    activeGroup = null;
    renderSystem();
    return { noBar, allOnly, badgeCount: badgeTexts.length };
  });
  check(singleGroupState.noBar,
    'system: forcing every resource into one group renders no environments chip row');
  check(singleGroupState.allOnly,
    `system: every box still carries its (single, forced) group badge with no chip row (${singleGroupState.badgeCount} badges)`);
}
async function main() {
  const mapPath = process.argv[2];
  if (!mapPath) {
    console.error('usage: node qa/map-qa.mjs <path-to-codemap.html>');
    process.exit(1);
  }
  const absMapPath = path.resolve(mapPath);
  if (!fs.existsSync(absMapPath)) {
    console.error('FAIL map file not found: ' + absMapPath);
    process.exit(1);
  }
  const mapDir = path.dirname(absMapPath); // <root>/.codemap
  const qaOutDir = path.join(mapDir, 'qa');
  fs.mkdirSync(qaOutDir, { recursive: true });
  const label = path.basename(path.dirname(mapDir)); // repo dir name, for screenshot naming

  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });

  const pageErrors = [];
  // A javascript: URL that actually executes surfaces as a dialog, so the
  // poisoned-deployed.json check below can prove the exploit, not just the
  // markup. Auto-dismissed so a fired alert can never hang the run.
  const dialogs = [];
  page.on('dialog', async (d) => { dialogs.push(d.message()); await d.dismiss().catch(() => {}); });
  page.on('pageerror', (err) => pageErrors.push(err.message || String(err)));
  page.on('console', (msg) => {
    if (msg.type() === 'error') pageErrors.push('console.error: ' + msg.text());
  });

  await page.goto(pathToFileURL(absMapPath).href);
  await page.waitForTimeout(150); // initial render (Overview tab, boxes rise-animate in)

  check(pageErrors.length === 0, `no pageerror on load${pageErrors.length ? ' (' + pageErrors.join(' | ') + ')' : ''}`);

  // ---- 2. Overview / System tabs render + screenshot ----
  await page.click('.tab[data-tab="overview"]');
  await page.waitForTimeout(150);
  const overviewBoxes = await page.locator('#canvas .box').count();
  check(overviewBoxes > 0, `overview tab renders boxes (${overviewBoxes})`);
  await page.screenshot({ path: path.join(qaOutDir, `${label}-overview.png`) });

  await page.click('.tab[data-tab="system"]');
  await page.waitForTimeout(150);
  const systemRendered = await page.locator('#canvas').isVisible();
  check(systemRendered, 'system tab renders');
  await settle(page);
  await page.screenshot({ path: path.join(qaOutDir, `${label}-system.png`) });
  await testSystemTab(page, qaOutDir, label, { pageErrors, dialogs });

  // ---- 3. Code tab: root + two densest drillable levels ----
  await page.click('.tab[data-tab="code"]');
  await page.waitForTimeout(150);

  const tree = await page.evaluate(() => DATA.tree);
  const SYMBOL_KINDS = new Set(['fn', 'class', 'method']);
  function boxChildrenOf(node) {
    return node.kind === 'file' ? (node.symbols || []) : (node.children || []);
  }
  function isDrillableDir(node) {
    return node.kind !== 'file' && !SYMBOL_KINDS.has(node.kind) && (node.children || []).length > 0;
  }

  // Walk the tree up to depth 3 collecting every drillable dir/repo/group
  // node, then pick the two densest by edge count (falling back to child
  // count, then name, for determinism). Edge count — not raw child count —
  // is what actually triggers pruning (needsChip = edges.length > 10 in
  // renderCode), so it's what "densest" means for this defect: a wrapper
  // dir with one child (e.g. "src" containing only "pli") can have zero
  // children-count signal at its own level while its child is where the
  // real edge density (and therefore the pruning/dead-zone bug) lives.
  // A pure greedy "follow the child with the most children" walk misses
  // that case, so this does a bounded full search instead.
  const candidates = [];
  function collect(node, depth, names) {
    if (depth > 3) return;
    for (const c of node.children || []) {
      if (!isDrillableDir(c)) continue;
      const nextNames = names.concat(c.name);
      candidates.push({ node: c, names: nextNames });
      collect(c, depth + 1, nextNames);
    }
  }
  collect(tree, 1, []);
  candidates.sort((a, b) =>
    (b.node.edges || []).length - (a.node.edges || []).length ||
    (b.node.children || []).length - (a.node.children || []).length ||
    a.node.name.localeCompare(b.node.name)
  );
  const denseLevels = candidates.slice(0, 2);

  const levelsToTest = [{ label: 'root', names: [] }].concat(
    denseLevels.map((c, i) => ({
      label: `dense-${i + 1} (${c.names.join('/')}, ${(c.node.edges || []).length} edges)`,
      names: c.names,
      densest: i === 0,
    }))
  );

  if (denseLevels.length === 0) {
    console.log('note: no drillable dense levels found below root (shallow/flat repo) — testing root only');
  }

  for (const lvl of levelsToTest) {
    await testCodeLevel(page, lvl.label, lvl.names, !!lvl.densest);
  }

  // drill to a level by name (state-set, not simulated clicks — navigation
  // itself isn't the thing under test; hover/chip/lens interactions ARE).
  async function gotoLevel(page, names) {
    await page.evaluate(() => { path = [DATA.tree]; closePeek(); renderCode(); });
    for (const name of names) {
      const ok = await page.evaluate((n) => {
        const kids = (path[path.length - 1].children || []);
        const child = kids.find((k) => k.name === n);
        if (!child) return false;
        path.push(child);
        renderCode();
        return true;
      }, name);
      if (!ok) return false;
    }
    await page.waitForTimeout(120);
    return true;
  }

  // Every currently-displayed edge label vs every box, in page coordinates.
  // Overlap counts only when BOTH axes overlap by more than the tolerance, so a
  // label merely grazing a box corner by a pixel isn't reported as a collision.
  async function labelBoxCollisions(page, tol) {
    return page.evaluate((tolerance) => {
      const vis = (el) => {
        const s = getComputedStyle(el);
        return s.display !== 'none' && s.visibility !== 'hidden' && parseFloat(s.opacity || '1') > 0.05;
      };
      const labels = [...document.querySelectorAll('#canvas svg text.flow-label')].filter(vis);
      const boxes = [...document.querySelectorAll('#canvas .box')].filter(vis);
      const hits = [];
      for (const l of labels) {
        const lr = l.getBoundingClientRect();
        if (lr.width === 0 || lr.height === 0) continue;
        for (const b of boxes) {
          const br = b.getBoundingClientRect();
          const ow = Math.min(lr.right, br.right) - Math.max(lr.left, br.left);
          const oh = Math.min(lr.bottom, br.bottom) - Math.max(lr.top, br.top);
          if (ow > tolerance && oh > tolerance) {
            hits.push(`"${l.textContent}" x "${b.dataset.boxname || '?'}" (${Math.round(ow)}x${Math.round(oh)}px)`);
          }
        }
      }
      return { labels: labels.length, hits };
    }, tol);
  }

  async function testCodeLevel(page, levelLabel, names, densest) {
    if (!(await gotoLevel(page, names))) {
      check(false, `${levelLabel}: could not drill into ${names.join('/')}`);
      return;
    }

    const levelInfo = await page.evaluate(() => {
      const c = path[path.length - 1];
      const kidsRaw = c.kind === 'file' ? (c.symbols || []) : (c.children || []);
      return {
        curName: c.name,
        boxNames: kidsRaw.map((k) => k.name),
        edges: (c.edges || []).map((e) => ({ source: e.source, target: e.target })),
      };
    });

    console.log(`-- code level "${levelLabel}" = ${levelInfo.curName} (${levelInfo.boxNames.length} boxes, ${levelInfo.edges.length} edges) --`);

    // zero duplicate (src,dst) paths in DATA at this level
    const pairKeys = levelInfo.edges.map((e) => `${e.source} ${e.target}`);
    const seen = new Set();
    const dupes = pairKeys.filter((k) => (seen.has(k) ? true : (seen.add(k), false)));
    check(dupes.length === 0, `${levelLabel}: zero duplicate (src,dst) edges in DATA (found ${dupes.length})`);

    // zero duplicate (src,dst) SVG path elements actually drawn
    const domDupCheck = await page.evaluate(() => {
      const svg = document.querySelector('#canvas svg');
      if (!svg) return { total: 0, dupes: 0 };
      const seen = new Set();
      let dupes = 0;
      svg.querySelectorAll('path.flow-line[data-src]').forEach((el) => {
        const key = el.dataset.src + ' ' + el.dataset.dst;
        if (seen.has(key)) dupes++; else seen.add(key);
      });
      return { total: svg.querySelectorAll('path.flow-line[data-src]').length, dupes };
    });
    check(domDupCheck.dupes === 0, `${levelLabel}: zero duplicate (src,dst) DOM path elements (${domDupCheck.total} paths drawn, ${domDupCheck.dupes} dupes)`);
    // one path per DATA edge, exactly (guarantee-by-construction check)
    check(domDupCheck.total === levelInfo.edges.length,
      `${levelLabel}: DOM path count (${domDupCheck.total}) equals DATA edge count (${levelInfo.edges.length})`);

    // canvas usage: the union bounding box of this level's boxes, in layout
    // (not clipped-viewport) coordinates, must cover a real share of the page.
    // Guards the letterbox regression: the old fixed 100x62 unit canvas pinned
    // every level into a strip near the top no matter how much room there was.
    if (levelInfo.boxNames.length > 6) {
      await settle(page);
      const usage = await page.evaluate(() => {
        const boxes = [...document.querySelectorAll('#canvas .box')];
        if (!boxes.length) return null;
        let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
        for (const b of boxes) {
          x0 = Math.min(x0, b.offsetLeft); y0 = Math.min(y0, b.offsetTop);
          x1 = Math.max(x1, b.offsetLeft + b.offsetWidth);
          y1 = Math.max(y1, b.offsetTop + b.offsetHeight);
        }
        return { w: x1 - x0, h: y1 - y0, vw: window.innerWidth, vh: window.innerHeight };
      });
      // Band, not a floor. Too small and the level is letterboxed into a strip
      // (the pre-dagre defect); too large and it sprawls across screens of empty
      // canvas, which wastes the page just as badly in the other direction.
      // Above 15 boxes only the floor applies: those levels legitimately scroll.
      // Area alone is too loose to catch sprawl: the pre-tightening 2743px-wide
      // layout still scored 202%, under the ceiling, purely because it was short.
      // The width bound is what actually bites, and it is the thing the layout
      // targets (1.4x viewport width, with tolerance here for measurement drift).
      const banded = levelInfo.boxNames.length <= 15;
      const hi = banded ? 250 : Infinity;
      const maxW = banded ? usage.vw * 1.5 : Infinity;
      const pct = usage ? (usage.w * usage.h) / (usage.vw * usage.vh) * 100 : 0;
      const dims = usage ? `, ${Math.round(usage.w)}x${Math.round(usage.h)} in ${usage.vw}x${usage.vh}` : '';
      check(usage !== null && pct >= 40 && pct <= hi && usage.w <= maxW,
        `${levelLabel}: boxes cover ${banded ? '40-250% of viewport area and stay within 1.5x its width' : '>=40% of viewport area'} (${pct.toFixed(0)}%${dims})`);
    }

    // hover every box, assert lit-path count == that box's DATA edge count,
    // and (densest level only) that no visible label lands on a box
    let hoverFailures = 0;
    let labelHits = [], labelsSeen = 0;
    for (const name of levelInfo.boxNames) {
      const expected = levelInfo.edges.filter((e) => e.source === name || e.target === name).length;
      const locator = page.locator(`.box[data-boxname="${escAttr(name)}"]`);
      const count = await locator.count();
      if (count === 0) {
        // symbol-kind levels (functions) have no layout/edges at all — skip silently
        if (levelInfo.edges.length === 0 && levelInfo.boxNames.length && expected === 0) continue;
        hoverFailures++;
        console.log(`  FAIL ${levelLabel}: box "${name}" not found in DOM to hover`);
        continue;
      }
      await locator.hover();
      await page.waitForTimeout(30);
      const litCount = await page.evaluate(() => {
        const svg = document.querySelector('#canvas svg');
        if (!svg) return 0;
        return [...svg.querySelectorAll('path.flow-line.edge-lit')]
          .filter((el) => getComputedStyle(el).display !== 'none').length;
      });
      if (litCount !== expected) {
        hoverFailures++;
        console.log(`  FAIL ${levelLabel}: hover "${name}" expected ${expected} lit paths, got ${litCount}`);
      }
      if (densest) {
        const col = await labelBoxCollisions(page, 4);
        labelsSeen += col.labels;
        col.hits.forEach((h) => labelHits.push(`hover "${name}": ${h}`));
      }
      await page.mouse.move(0, 0);
      await page.waitForTimeout(15);
    }
    check(hoverFailures === 0, `${levelLabel}: every box's hover lit-count matches its DATA edge count (${levelInfo.boxNames.length} boxes checked, ${hoverFailures} mismatched)`);
    if (densest) {
      labelHits.slice(0, 6).forEach((h) => console.log('  ' + h));
      check(labelHits.length === 0,
        `${levelLabel}: no visible edge label overlaps a box by >4px (${labelsSeen} label sightings, ${labelHits.length} collisions)`);
    }

    // prune chip toggle, if present at this level
    const chipCount = await page.locator('#edgeChip').count();
    if (chipCount > 0) {
      const hiddenBefore = await page.evaluate(() =>
        document.querySelectorAll('#canvas svg path.flow-line.edge-hidden').length);
      await page.click('#edgeChip');
      await page.waitForTimeout(60);
      const hiddenAfterShowAll = await page.evaluate(() =>
        document.querySelectorAll('#canvas svg path.flow-line.edge-hidden').length);
      check(hiddenAfterShowAll === 0, `${levelLabel}: chip "show all" drops hidden-edge count to zero (was ${hiddenBefore}, now ${hiddenAfterShowAll})`);
      await page.click('#edgeChip');
      await page.waitForTimeout(60);
      const hiddenRestored = await page.evaluate(() =>
        document.querySelectorAll('#canvas svg path.flow-line.edge-hidden').length);
      check(hiddenRestored === hiddenBefore, `${levelLabel}: chip toggle back restores hidden-edge count (${hiddenBefore} -> 0 -> ${hiddenRestored})`);
    } else {
      console.log(`  (no prune chip at "${levelLabel}" — ${levelInfo.edges.length} edges, chip only appears above 10)`);
    }
  }

  // ---- 4. Lenses ----
  const lensNames = await page.evaluate(() => Object.keys((DATA.labels && DATA.labels.lenses) || {}));
  if (lensNames.length) {
    // Lens rendering at the densest level: a lit arrow must land on a box the
    // reader can actually see. The defect this catches is an arrow drawn lit
    // into apparent blackness because its endpoint lost .lit (or was dimmed to
    // the point of invisibility) in the layout path that drew the arrow.
    if (denseLevels.length && (await gotoLevel(page, denseLevels[0].names))) {
      let unlitEnds = 0, tooFaint = 0, litEdges = 0, boxesSeen = 0;
      for (const lensName of lensNames) {
        await page.evaluate((n) => {
          const el = [...document.querySelectorAll('#lensbar .lens')].find((l) => l.dataset.lens === n);
          if (el) el.click();
        }, lensName);
        await page.waitForTimeout(60);
        await settle(page);
        const r = await page.evaluate(() => {
          const boxes = {};
          for (const b of document.querySelectorAll('#canvas .box[data-boxname]')) {
            boxes[b.dataset.boxname] = {
              lit: b.classList.contains('lit'),
              op: parseFloat(getComputedStyle(b).opacity || '1'),
            };
          }
          const bad = [], faint = [];
          for (const name of Object.keys(boxes)) {
            if (boxes[name].op < 0.4) faint.push(`${name} @${boxes[name].op.toFixed(2)}`);
          }
          let lit = 0;
          for (const p of document.querySelectorAll('#canvas svg path.flow-line[data-lens-lit="1"]')) {
            lit++;
            for (const end of [p.dataset.src, p.dataset.dst]) {
              const b = boxes[end];
              if (!b || !b.lit || b.op < 0.9) {
                bad.push(`${p.dataset.src}->${p.dataset.dst} end "${end}" ` +
                  (b ? `lit=${b.lit} opacity=${b.op.toFixed(2)}` : 'box missing'));
              }
            }
          }
          return { bad, faint, lit, boxes: Object.keys(boxes).length };
        });
        litEdges += r.lit; boxesSeen += r.boxes;
        unlitEnds += r.bad.length; tooFaint += r.faint.length;
        r.bad.slice(0, 4).forEach((b) => console.log(`  lens "${lensName}": lit edge into a non-lit box: ${b}`));
        r.faint.slice(0, 4).forEach((f) => console.log(`  lens "${lensName}": box below the dim floor: ${f}`));
        await page.evaluate((n) => {
          const el = [...document.querySelectorAll('#lensbar .lens')].find((l) => l.dataset.lens === n);
          if (el) el.click();
        }, lensName);
        await page.waitForTimeout(50);
      }
      check(unlitEnds === 0,
        `lens-lit arrows land on lit boxes: both endpoints .lit and opacity >=0.9 (${litEdges} lit edges across ${lensNames.length} lenses, ${unlitEnds} bad endpoints)`);
      check(tooFaint === 0,
        `lens dim floor: every box stays at opacity >=0.4 (${boxesSeen} box readings, ${tooFaint} below floor)`);
    }

    // back to root for a clean, full-tree lens check
    await page.evaluate(() => { path = [DATA.tree]; closePeek(); renderCode(); });
    let firstLensShot = false;
    for (const lensName of lensNames) {
      const stateCheck = await page.evaluate((name) => {
        const lensbar = document.getElementById('lensbar');
        const el = [...lensbar.querySelectorAll('.lens')].find((l) => l.dataset.lens === name);
        if (!el) return { ok: false, reason: 'lens chip not found' };
        el.click();
        const boxes = [...document.querySelectorAll('#canvas .box[data-boxname]')];
        const bad = boxes.filter((b) => {
          const lit = b.classList.contains('lit');
          const dimmed = b.classList.contains('dimmed');
          return lit === dimmed; // both true or both false = third state
        });
        return { ok: bad.length === 0, total: boxes.length, bad: bad.length };
      }, lensName);
      check(stateCheck.ok, `lens "${lensName}": every box is .lit xor .dimmed (${stateCheck.total ?? 0} boxes, ${stateCheck.bad ?? '?'} bad${stateCheck.reason ? ' — ' + stateCheck.reason : ''})`);
      await page.waitForTimeout(120);
      if (!firstLensShot) {
        await page.screenshot({ path: path.join(qaOutDir, `${label}-lens-${lensName.replace(/[^a-z0-9-]+/gi, '_')}.png`) });
        firstLensShot = true;
      }
      // deactivate (lens click toggles) so the next lens starts clean
      await page.evaluate((name) => {
        const lensbar = document.getElementById('lensbar');
        const el = [...lensbar.querySelectorAll('.lens')].find((l) => l.dataset.lens === name);
        if (el) el.click();
      }, lensName);
      await page.waitForTimeout(60);
    }
  } else {
    console.log('note: no lenses defined in this map — skipping lens checks');
  }

  // ---- Exclusive focus: lens active AND a box hovered ----
  // The bug this catches: a lens lights its own flow persistently, so hovering
  // a box used to show the union (lens edges + hover edges) and the level read
  // as noise. Hover must win outright for its duration, and letting go must put
  // the lens resting state back exactly as it was.
  if (lensNames.length && denseLevels.length) {
    const dl = denseLevels[0];
    if (!(await gotoLevel(page, dl.names))) {
      check(false, `exclusive focus: could not drill into ${dl.names.join('/')}`);
    } else {
      const info = await page.evaluate(() => {
        const c = path[path.length - 1];
        const kidsRaw = c.kind === 'file' ? (c.symbols || []) : (c.children || []);
        return {
          boxNames: kidsRaw.map((k) => k.name),
          edges: (c.edges || []).map((e) => ({ source: e.source, target: e.target })),
        };
      });
      const clickLens = (name) => page.evaluate((n) => {
        const el = [...document.querySelectorAll('#lensbar .lens')].find((l) => l.dataset.lens === n);
        if (el) el.click();
      }, name);
      const visibleState = () => page.evaluate(() => {
        const svg = document.querySelector('#canvas svg');
        if (!svg) return { lit: 0, labels: [] };
        const shown = (el) => getComputedStyle(el).display !== 'none';
        return {
          lit: [...svg.querySelectorAll('path.flow-line.edge-lit')].filter(shown).length,
          labels: [...svg.querySelectorAll('text.flow-label')].filter(shown)
            .map((el) => el.dataset.src + '→' + el.dataset.dst),
        };
      });
      let exclusiveBad = 0, restingBad = 0, hovers = 0;
      for (const lensName of lensNames) {
        await clickLens(lensName);
        await page.waitForTimeout(90);
        const resting = await visibleState();
        for (const name of info.boxNames) {
          const expected = info.edges.filter((e) => e.source === name || e.target === name).length;
          const loc = page.locator(`.box[data-boxname="${escAttr(name)}"]`);
          if ((await loc.count()) === 0) continue;
          await loc.hover();
          await page.waitForTimeout(30);
          hovers++;
          const st = await visibleState();
          const stray = st.labels.filter((l) => !l.startsWith(name + '→') && !l.endsWith('→' + name));
          if (st.lit !== expected || stray.length) {
            exclusiveBad++;
            console.log(`  FAIL lens "${lensName}" + hover "${name}": expected ${expected} lit edges, got ${st.lit}` +
              (stray.length ? `; ${stray.length} stray lens label(s): ${stray.join(', ')}` : ''));
          }
          await page.mouse.move(0, 0);
          await page.waitForTimeout(25);
        }
        const after = await visibleState();
        if (after.lit !== resting.lit || after.labels.length !== resting.labels.length) {
          restingBad++;
          console.log(`  FAIL lens "${lensName}": resting state not restored (${resting.lit} lit/${resting.labels.length} labels -> ${after.lit}/${after.labels.length})`);
        }
        await clickLens(lensName);
        await page.waitForTimeout(60);
      }
      check(exclusiveBad === 0,
        `exclusive focus: lens + hover lights only the hovered box's edges (${hovers} lens/box hovers, ${exclusiveBad} showed the lens+hover union)`);
      check(restingBad === 0,
        `lens resting state returns exactly on mouseleave (${lensNames.length} lenses, ${restingBad} drifted)`);
    }
  }

  await browser.close();

  const failed = results.filter((r) => !r.ok);
  console.log('');
  console.log(`SUMMARY: ${results.length - failed.length}/${results.length} checks passed`);
  if (failed.length) {
    console.log('FAILED CHECKS:');
    failed.forEach((f) => console.log('  - ' + f.label));
    process.exit(1);
  }
  process.exit(0);
}

main().catch((err) => {
  console.error('FAIL map-qa crashed: ' + (err && err.stack || err));
  process.exit(1);
});
